### ISSUE TITLE
Connection via Remoteit no function

### ISSUE THREAD

**Issue by proellfabian** [raven-worx/loveboxpi#9]
I tried to install loveboxpi according to your instructions, which also worked without problems.
Unfortunately I can not access the web dashboard and also can not connect correctly to the remoteit service. can you please help me and describe how the correct setup after installation and donwload all files works?

**Comment by proellfabian** [comment]
Hi thanks for the fast reply,

I was able to correctly install remoteit and installed the 1.0.4 version of your project as described. But i cannot access the web interface at all.

**Comment by proellfabian** [comment]
As well as remoteit is asking me for a type of service and i don't really know which one to use, nor how to configure it.

**Comment by raven-worx** [comment]
How did you install remoteit exactly?
Via the web interface or already how described in the link i've posted?

The link already has instructions how to add a service. HTTP for the WebInterface.

**Comment by proellfabian** [comment]
installed it via the new link. 
tried to configure the web interface (see pictures)
all the webinterface says is:  _403 connecion not available_
![image](https://user-images.githubusercontent.com/127743905/227259246-977d27bf-87e0-4637-9bbb-b4a530982c63.png)
![image](https://user-images.githubusercontent.com/127743905/227259489-6d244886-977d-40af-825d-f4b20dc20855.png)

**Comment by proellfabian** [comment]
cant see port and so on of the loveboxpi service in cli as well...

**Comment by raven-worx** [comment]
i just tried it on my device

You can either use the old remote.it cli client (extract it to /usr/local/bin) and use the webinterface as it is. The whole registration process with this client still seems to work.
[remoteit.old.tar.gz](https://github.com/raven-worx/loveboxpi/files/11063831/remoteit.old.tar.gz)

Or with the new way (webinterface needs an update to support this way):
1. download the install script as described [here](https://www.remote.it/getting-started/raspberry-pi) and make sure to select HTTP service
2. copy the CLAIM code and go back to http://app.remote.it, click add device again and in the top enter the claim code
3. check that there is a HTTP service added to the device (no special settings are required) or add it there
4. on the loveboxpi device call `systemctl restart remoteit-refresh.service` or simply restart the device

**Comment by proellfabian** [comment]
Thanks for the help, working just fine now :)
Great project!
